### ISSUE TITLE
Field for late starters, i.e. "Did not play on X days"

### ISSUE THREAD

**Issue by guidokl** [sophice/ow2-battle-pass-calculator#3]
Hey! Nice tool you made there. I like the functionality and the design!
Since I did not start to play at release, It would be great to have a field like: 

- "Playing since X days"
- "Started at XX.XX.XX"
- "Did not play on X days"

The last variant is probably most versatile, as you could also use it for holiday or other off days.

**Comment by sophice** [comment]
Glad you like it!

This wouldn't affect the "expected finish" box, since that is based only on the days going forward, and just adds in your current tier/XP. For the "projected finish", I suppose that could be handy, to effectively set the start date of your earnings to something other than the actual start date. If we're 6 weeks in to the season and you only started playing a week ago, then yeah in that case you're right and the projection is pretty far off.

I was thinking of adding an "advanced mode" where you could change a few extra things, and changing the start date was one of them, for people that just want to mess with it and see how the numbers change. Technically that would cover such a use case, but wouldn't be very obvious to users.

Alternatively, I could maybe add some settings down below inside the "projected finish" area to tweak those numbers like you said. That might be the clearest way. I want to minimize how much I ask for input up top to avoid confusing people, so putting it down below might make it more obvious what it affects and how.

Thanks for the suggestion, I'll spend some more time thinking on it!

**Comment by sophice** [comment]
I've added a "Days missed" field with the latest update (and also updated the start/end dates for season 2). Sorry it's too late for season 1 but hopefully people will find it useful in future seasons!

I'm also working on a "Days you will miss" field that will do the opposite, for if you plan on taking a vacation or other extended and planned time off the game in the future. This would affect the "expected" sections in a similar way. The work is partly done, hopefully I can get that up in the next week to help people out in season 2.
