### ISSUE TITLE
Expected finish time seems incorrect

### ISSUE THREAD

**Issue by rufusw** [sophice/ow2-battle-pass-calculator#4]
I am currently at tier 21, yet my expected finish is in 7 days? 

My weekly pace is 12 tiers, therefore I should be at tier 33 in 7 days, far from finished. 

Is this a bug or have I made a mistake?

https://sophice.github.io/ow2-battle-pass-calculator/#t=22&x=1240&p=7&d=3&m=5&v=1212&w=3

Also, minor quibble here: the game uses the term 'current tier' to mean the last tier you completed (it says it on the left of the match reward screen), whereas you use current tier to mean the tier you have yet to complete.

Thanks for making the calculator!

**Comment by sophice** [comment]
Thanks for the share link, I will investigate. I'm going to see if I can set up proper unit testing, to help make sure things like this don't happen. Too many scenarios to manually test well.

I'll put some thought in to the presentation of "current tier". I felt this was the clearest way to do it, but I'll think some more. I tend to look at the battle pass section in game, and on there the progress line shows the current tier you're working on, so that felt the most obvious to put. The "current tier you're working on". Hard to say what most people would prefer without a poll or something. Maybe just tweaking the labels on the fields would make it clearer... I'll finish working on the unit testing and then come back to that.

**Comment by sophice** [comment]
So I loaded up your link and it's not showing me the same thing that you are seeing. I see your projected finish as missing 35 tiers, and your expected finish as missing 2 tiers. You might have an outdated version of the page cached in your browser, try clearing your cache and see if you get a different result?

**Comment by rufusw** [comment]
Thanks for taking a look at my link.

The bug only appears when the expected finish reaches 100% completion, so if you increase the tier to 24 today, it says finished in 4 more days. If you increase it to tier 34 it says 0 days to finish. 
https://sophice.github.io/ow2-battle-pass-calculator/#t=34&x=1240&p=7&d=3&m=5&v=1212&w=3

To be sure I just tested in a different browser and its the same result.

About the current tier ambiguity - a small tweak to the label sounds best in my opinion.

**Comment by sophice** [comment]
I see now. I THINK I've fixed it, try now and let me know if it looks right.

**Comment by rufusw** [comment]
Yes I think you fixed it, looks fine to me now. Thanks!
